<?php

return [

  'exclusives_time' => "+10 minutes",

  'items' => [
    'status'          => [
      '0' => '販売前',
      '1' => '販売中',
      '2' => '売却済み',
    ],
    'items_status'    => [
      '0' => '新品',
      '1' => 'キズあり',
      '2' => 'ジャンク',
    ],
    'delivery_charge' => [
      '0' => '配送料を含む',
      '1' => '着払い',
    ],
    'delivery_plan'   => [
      '0' => '郵送',
      '1' => 'ヤマト',
    ],
    'delivery_date'   => [
      '0' => '1周間以内',
      '1' => '3日以内',
      '2' => '1日以内',
      '3' => '当日',
    ],
  ],

  'pref' => [
    '1'  => '北海道',
    '2'  => '青森県',
    '3'  => '岩手県',
    '4'  => '宮城県',
    '5'  => '秋田県',
    '6'  => '山形県',
    '7'  => '福島県',
    '8'  => '茨城県',
    '9'  => '栃木県',
    '10' => '群馬県',
    '11' => '埼玉県',
    '12' => '千葉県',
    '13' => '東京都',
    '14' => '神奈川県',
    '15' => '新潟県',
    '16' => '富山県',
    '17' => '石川県',
    '18' => '福井県',
    '19' => '山梨県',
    '20' => '長野県',
    '21' => '岐阜県',
    '22' => '静岡県',
    '23' => '愛知県',
    '24' => '三重県',
    '25' => '滋賀県',
    '26' => '京都府',
    '27' => '大阪府',
    '28' => '兵庫県',
    '29' => '奈良県',
    '30' => '和歌山県',
    '31' => '鳥取県',
    '32' => '島根県',
    '33' => '岡山県',
    '34' => '広島県',
    '35' => '山口県',
    '36' => '徳島県',
    '37' => '香川県',
    '38' => '愛媛県',
    '39' => '高知県',
    '40' => '福岡県',
    '41' => '佐賀県',
    '42' => '長崎県',
    '43' => '熊本県',
    '44' => '大分県',
    '45' => '宮崎県',
    '46' => '鹿児島県',
    '47' => '沖縄県',
  ],

  'shuzo' => [
    '1'  => 'https://drive.google.com/file/d/0B52zasmSZm2AazM3eU1DbjRXSkk/view?usp=sharing',
    '2'  => 'https://drive.google.com/file/d/0B52zasmSZm2AWDJ5eS1lZWhoejQ/view?usp=sharing',
    '3'  => 'https://drive.google.com/file/d/0B52zasmSZm2AaDkwLW1mRzUwWkU/view?usp=sharing',
    '4'  => 'https://drive.google.com/file/d/0B52zasmSZm2ASmtkY2xDUUFuQ0k/view?usp=sharing',
    '5'  => 'https://drive.google.com/file/d/0B52zasmSZm2AYkhrRGJRQmRSOUE/view?usp=sharing',
    '6'  => 'https://drive.google.com/file/d/0B52zasmSZm2AZnpuRlVxYjBiYXM/view?usp=sharing',
    '7'  => 'https://drive.google.com/file/d/0B52zasmSZm2AWnp4MmxueFNTblU/view?usp=sharing',
    '8'  => 'https://drive.google.com/file/d/0B52zasmSZm2ANVhJS0NnSzJPYWM/view?usp=sharing',
    '9'  => 'https://drive.google.com/file/d/0B52zasmSZm2AcG4xWUl0SUdzMkU/view?usp=sharing',
    '10' => 'https://drive.google.com/file/d/0B52zasmSZm2AdFFZYzhaODJRNkU/view?usp=sharing',
    '11' => 'https://drive.google.com/file/d/0B52zasmSZm2ARkt5UGt6M2ZwU00/view?usp=sharing',
    '12' => 'https://drive.google.com/file/d/0B52zasmSZm2ARVg4TVRhSDhLNmc/view?usp=sharing',
    '13' => 'https://drive.google.com/file/d/0B52zasmSZm2AeXlkSlctbjFsRFU/view?usp=sharing',
    '14' => 'https://drive.google.com/file/d/0B52zasmSZm2ANXVNV2tNa1JsY2M/view?usp=sharing',
    '15' => 'https://drive.google.com/file/d/0B52zasmSZm2AbTJZT2hwRUtJakU/view?usp=sharing',
    '16' => 'https://drive.google.com/file/d/0B52zasmSZm2AYmNab1cxMFgtb0E/view?usp=sharing',
    '17' => 'https://drive.google.com/file/d/0B52zasmSZm2AcGZYQ3JEOEN0Szg/view?usp=sharing',
    '18' => 'https://drive.google.com/file/d/0B52zasmSZm2AZ1M5N3NmT3NkVzQ/view?usp=sharing',
    '19' => 'https://drive.google.com/file/d/0B52zasmSZm2AN3hISmxqc0ozUDA/view?usp=sharing',
    '20' => 'https://drive.google.com/file/d/0B52zasmSZm2AaE8zalJLZVRxSDQ/view?usp=sharing',
    '21' => 'https://drive.google.com/file/d/0B52zasmSZm2AbTZmOVM4cjB4OGs/view?usp=sharing',
    '22' => 'https://drive.google.com/file/d/0B52zasmSZm2AZjNRUWNSb09tX2c/view?usp=sharing',
    '23' => 'https://drive.google.com/file/d/0B52zasmSZm2ARzZpMTRmUlg2NHM/view?usp=sharing',
    '24' => 'https://drive.google.com/file/d/0B52zasmSZm2AZXdaZzA0OEdETTQ/view?usp=sharing',
    '25' => 'https://drive.google.com/file/d/0B52zasmSZm2AUHdZMl9GM1N4aEU/view?usp=sharing',
    '26' => 'https://drive.google.com/file/d/0B52zasmSZm2AYlNJOXYxZkVNekE/view?usp=sharing',
    '27' => 'https://drive.google.com/file/d/0B52zasmSZm2AOF9mbGhHTklWaVU/view?usp=sharing',
    '28' => 'https://drive.google.com/file/d/0B52zasmSZm2AZHFtYzJMTDZGNDA/view?usp=sharing',
    '29' => 'https://drive.google.com/file/d/0B52zasmSZm2ASzA4SU40aEFBNmM/view?usp=sharing',
    '30' => 'https://drive.google.com/file/d/0B52zasmSZm2AY25vZjNMRE1tVmM/view?usp=sharing',
    '31' => 'https://drive.google.com/file/d/0B52zasmSZm2ATW84NTJkTS0xRkE/view?usp=sharing',
  ],

];
